[package]
name = "celestial-echo"
version = "0.1.0"
authors = ["Caleb Jones <code@calebjones.net>"]

[dependencies]
egg-mode = "0.12"
diesel = { version = "1.1", features = ["sqlite", "chrono"] }
chrono = "0.4"
failure = "0.1"
tokio-core = "0.1"
regex = "0.2"